#!/usr/bin/env python3
# Generates wrappers.inc: classes that forward IDirect3D8 and IDirect3DDevice8 to DXVK, from the
# method lists in d3d8.h. Methods named in OVERRIDES are written by hand in dxvk_adapter.cpp.
# Usage: generate_wrappers.py <d3d8.h> <wrappers.inc>
import re, sys

OVERRIDES = {
    'IDirect3D8': {'QueryInterface', 'AddRef', 'Release', 'CreateDevice'},
    'IDirect3DDevice8': {'QueryInterface', 'AddRef', 'Release', 'GetDirect3D', 'Reset', 'Present', 'CreateAdditionalSwapChain'},
}

def methods(header, iface):
    m = re.search(r'DECLARE_INTERFACE_\(' + iface + r',\s*IUnknown\)\s*\{(.*?)\};', header, re.S)
    out = []
    for line in m.group(1).splitlines():
        line = line.strip()
        mm = re.match(r'STDMETHOD(?:_\(\s*([^,]+?)\s*,\s*(\w+)\s*\)|\(\s*(\w+)\s*\))\s*\((.*)\)\s*PURE\s*;', line)
        if not mm:
            continue
        ret = mm.group(1) or 'HRESULT'
        name = mm.group(2) or mm.group(3)
        args = mm.group(4).strip()
        if args in ('THIS', ''):
            params = []
        else:
            params = [p.strip() for p in re.sub(r'^THIS_\s*', '', args).split(',')]
        out.append((ret, name, params))
    return out

def split_param(p, index):
    # Returns (declaration, name); unnamed parameters get one.
    words = [w for w in re.findall(r'\w+', re.sub(r'\[.*\]', '', p)) if w not in ('CONST', 'const', 'struct')]
    if len(words) >= 2:
        return p, words[-1]
    name = f'arg{index}'
    return f'{p} {name}', name

def emit(iface, cls, header):
    lines = [f'// Forwards {iface} to DXVK.', f'class {cls}Base : public {iface}', '{', 'public:',
             f'\texplicit {cls}Base({iface}* inner) : m_inner(inner) {{}}', f'\tvirtual ~{cls}Base() {{}}',
             f'\t{iface}* inner() const {{ return m_inner; }}', '']
    for ret, name, params in methods(header, iface):
        if name in OVERRIDES[iface]:
            continue
        split = [split_param(p, i) for i, p in enumerate(params)]
        decl = ', '.join(d for d, _ in split)
        call = ', '.join(n for _, n in split)
        if ret == 'HRESULT':
            lines.append(f'\tSTDMETHOD({name})({decl}) override {{ return m_inner->{name}({call}); }}')
        else:
            body = f'return m_inner->{name}({call});' if ret != 'void' else f'm_inner->{name}({call});'
            lines.append(f'\tSTDMETHOD_({ret}, {name})({decl}) override {{ {body} }}')
    lines += ['', 'protected:', f'\t{iface}* m_inner;', '};', '']
    return '\n'.join(lines)

header = open(sys.argv[1], encoding='latin1').read()
with open(sys.argv[2], 'w') as f:
    f.write('// Generated by generate_wrappers.py from d3d8.h. Do not edit.\n\n')
    f.write(emit('IDirect3D8', 'Direct3D8Wrapper', header))
    f.write(emit('IDirect3DDevice8', 'Device8Wrapper', header))
