"""Writes src/conquest/world.ts: the land outline of the world map, from Natural Earth's 1:110m land
polygons (public domain, https://www.naturalearthdata.com), in the map's equirectangular
coordinates: x = (longitude + 180) * 4, y = (85 - latitude) * 4. Antarctica is left out.

    python3 scripts/make_world.py [ne_110m_land.geojson]
"""
import json
import sys
import urllib.request

SOURCE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"


def project(lon, lat):
    return (lon + 180) * 4, (85 - lat) * 4


def main():
    if len(sys.argv) > 1:
        data = json.load(open(sys.argv[1]))
    else:
        data = json.load(urllib.request.urlopen(SOURCE))
    parts = []
    for feature in data["features"]:
        geometry = feature["geometry"]
        polygons = [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]
        for polygon in polygons:
            ring = polygon[0]
            if max(lat for _, lat in ring) < -55:
                continue
            points = [project(lon, lat) for lon, lat in ring]
            path = "M" + "L".join(f"{x:.1f} {y:.1f}" for x, y in points) + "Z"
            parts.append(path)
    with open("src/conquest/world.ts", "w") as out:
        out.write("// Generated by scripts/make_world.py from Natural Earth (public domain). Do not edit.\n")
        out.write("// Equirectangular: x = (longitude + 180) * 4, y = (85 - latitude) * 4.\n")
        out.write(f'export const LAND_PATH = "{"".join(parts)}";\n')


main()
